# -*- coding: utf-8 -*-
"""Loan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ECOdzrRbgyOIJgu4iBj8ALSJZZxCD7xk
"""

import numpy as np
import pandas as pd
import tensorflow as tf
tf.random.set_seed(3)
from tensorflow import keras

data=pd.read_csv('/content/loan_approval_dataset.csv')

data.head()

data.columns

X=data.drop(columns=[' education',' self_employed',' loan_status'],axis=1)
Y=data[' loan_status']
Y=Y.replace("Approved",1)
Y=Y.replace("Rejected",0)

model=keras.Sequential([
    keras.layers.Flatten(input_shape=(10,)),
    keras.layers.Dense(20,activation='relu'),
    keras.layers.Dense(2,activation='sigmoid')
])

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

print(X.dtypes)
print(Y.dtypes)

Y.head()

Y= Y.replace({" Approved": 1, " Rejected": 0})
Y.head()

X = np.array(X).astype(np.float32)  # Convert X to float32
Y = np.array(Y).astype(np.float32)  # Convert Y to float32

model.fit(X, Y, validation_split=0.1, epochs=10)

